version: '2'
services:
  web:
    image:  php:apache
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - "${PWD}/website:/var/www/html"
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api_network

  api:
    image: matao39/studentlist-webapp-api
    ports:
      - "8081:5000"
    volumes:
      - "${PWD}/simple_api/student_age.json:/data/student_age.json"
    networks:
      - api_network

networks:
  api_network: